packages:
  - name: HomiAI
    functions:
      - name: bot
        runtime: python:3.11
        web: raw
        main: main
        limits:
          timeout: 60000
        parameters:
          TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
          OPENAI_API_KEY: ${OPENAI_API_KEY}
